### ISSUE TITLE
Password and PanelID twisted

### ISSUE THREAD

**Issue by comino** [DEHBIF/LabelPrinterGui#1]
Using latest version on Ubuntu 17.10: 
On enteing: 
Pass: e8c52a31
and Panel-ID is : 001

I get a label with : 
Pass: 001
Panel-ID: e8c52a31

So those two are twisted. 

Screenshot: 
![screenshot from 2018-01-15 15-22-13](https://user-images.githubusercontent.com/4029642/34946707-2d4e0020-fa08-11e7-8c24-0a27d4c28e72.png)

**Comment by DEHBIF** [comment]
Fixed with: f7435f78ddbd8ca0f70eab9649cb7b432d15c955
Please reopen if issue persist.
